define

# ATTRIBUTES
storage_type sub attribute, value string;
name sub attribute, value string;
# physical_state sub attribute, value string;
product_type sub attribute, value string;
needs_packaging sub attribute, value boolean;


# ENTITIES
can_move sub entity,
  plays located_at:what;
 
product sub can_move,
    plays destination_at:what,
    owns storage_type,
    owns name,
    owns needs_packaging;
    # owns physical_state,
    # owns product_type;
  
freezer_goods sub product;
fresh_goods sub product;
shelf_goods sub product;


can_not_move sub entity;
location sub can_not_move,
  owns name,
  plays located_at:where,
  plays destination_at:where;

freezer sub location;
packing_station sub location;
shelf sub location;
loading_table sub location;


# RULES
rule shelf_goods_on_shelf:
  when {
    $prod isa shelf_goods;
  } then {
    $prod has storage_type "shelf";
  };
rule shelf_goods_dont_need_packaging:
when {
  $prod isa shelf_goods;
} then {
  $prod has needs_packaging false;
};

rule fresh_goods_on_shelf:
  when {
    $prod isa fresh_goods;
  } then {
    $prod has storage_type "shelf";
  };
rule fresh_goods_need_packaging:
  when {
    $prod isa fresh_goods;
  } then {
    $prod has needs_packaging true;
  };

rule freezer_goods_in_freezer:
  when {
    $prod isa freezer_goods;
  } then {
    $prod has storage_type "freezer";
  };
rule freezer_goods_dont_need_packaging:
  when {
    $prod isa freezer_goods;
  } then {
    $prod has needs_packaging false;
  };


# RELATIONS
located_at sub relation,
  relates where,
  relates what;

destination_at sub relation,
  relates where,
  relates what;


############################################################### old

# storage_type sub attribute, value string;
# name sub attribute, value string;
# physical_state sub attribute, value string;
# product_type sub attribute, value string;

# product sub entity,
#     owns storage_type,
#     owns name,
#     owns physical_state,
#     owns product_type;
  



# rule drink_never_in_freezer:
#   when {
#     $prod isa product, has physical_state "liquid";
#   } then {
#     $prod has storage_type "shelf" ;
#   };