insert
# PRODUCTS
$prod-1 isa product, has name "kroket1", has storage_type "freezer";
$prod-2 isa product, has name "hagelslag1", has storage_type "shelf";
$prod-3 isa product, has name "brood1", has storage_type "shelf";
$prod-4 isa product, has name "cola1", has physical_state "liquid";

$loc-1 isa loading_table, has name "loading_table1";

$dest-1 isa freezer, has name "freezer1";

$new_located_at (where: $loc-1, what: $prod-1) isa located_at;

$new_destination_at (where: $dest-1, what: $prod-1) isa destination_at;